[package]
name = "buildtool"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
glob = "0.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34-deprecated"
walkdir = "2.5.0"

[[bin]]
name = "buildtool"
path = "main.rs"

[profile.release]
debug = false
