blank_issues_enabled: false
contact_links:
  - name: Technical Questions / Help
    url: https://github.com/Jonathan1324/linked-assembly/discussions
    about: For general usage questions or architecture discussions.