name: build-test-macos

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: python3 scripts/install_build_deps.py
        shell: bash

      - name: Build the project
        run: python -m ci.ci --no-test -a -A linked-assembly-macos-arm
        shell: bash

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: linked-assembly-macos-arm
          path: dist/

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: linked-assembly-macos-arm-logs
          path: logs/