name: build

on:
    workflow_dispatch:  # TODO: currently only with UI

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Cache apt packages
            uses: actions/cache@v4
            with:
                path: /var/cache/apt/archives
                key: apt-cache-${{ runner.os }}-${{ hashFiles('**/apt-packages.txt') }}
                restore-keys: |
                    apt-cache-${{ runner.os }}-

          - name: Install build tools
            run: |
                sudo apt-get update
                sudo apt-get install -y build-essential
                sudo apt-get install -y nasm

          - name: Cache build directory
            uses: actions/cache@v4
            with:
                path: build/
                key: ${{ runner.os }}-build-${{ hashFiles('ci/build-version.txt') }}
                restore-keys:
                    ${{ runner.os }}-build-

          - name: Build the project
            run: make

          - name: Upload build artifacts
            uses: actions/upload-artifact@v4
            with:
                name: build-artifacts
                path: build/
