name: build-test-ubuntu

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm

      - name: Build the project
        run: make DEBUG=1
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-artifacts
          path: bin/

  test:
    needs: build

    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bin-artifacts
          path: bin