name: build-test-macos

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: brew install make nasm

      - name: Build the project
        run: make
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

  test:
    needs: build

    runs-on: macos-15

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build