name: build

on:
  workflow_dispatch:  # TODO: currently only with UI

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x86_64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm

      - name: Install build tools (Windows)
        if: runner.os == 'Windows'
        run: choco install make nasm

      - name: Install build tools (macOS)
        if: runner.os == 'macOS'
        run: brew install make nasm

      - name: Build the project
        run: make
        shell: bash

      - name: Move binaries
        run: |
          mkdir -p binaries
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            EXT=".exe"
          fi
          cp build/assembly/assembly$EXT binaries/assembly-${{ runner.os }}-${{ matrix.arch }}$EXT
          cp build/linker/linker$EXT binaries/linker-${{ runner.os }}-${{ matrix.arch }}$EXT
        shell: bash

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}-${{ matrix.arch }}
          path: binaries/