name: build-test-macos

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: python3 scripts/install_build_deps.py
        shell: bash

      - name: Build the project
        run: make DEBUG=1
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-artifacts
          path: bin/

  test:
    needs: build

    runs-on: macos-15

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bin-artifacts
          path: bin